### ISSUE TITLE
Make this repo public

### ISSUE THREAD

**Issue by paule96** [abeckDev/SampleKubernetesFiles#2]
Here a short todo list to make this repo public

## remove customers references

In some files are customer references, that you don't have permission to make them public. That must be removed. Please don't forget to clean up the git history. (yes you need a force push. Be careful)

## add a license

Add a license so other people can use the code in the repo. 

## Readme

Add a good readme to this repo to make shure external people has a easy start. a good example for a good readme is [https://t-systems-mms.github.io/phonebook/](https://t-systems-mms.github.io/phonebook/).

**Comment by abeckDev** [comment]
Thanks for the input. I plan to do the change at the end of this week. 
You review is highly appreciated :)

**Comment by abeckDev** [comment]
This Repository is now OpenSourced
I removed the customer content and rewrote the GitHistory.
I will track the upgrade Readme process in another Issue.
